<?php

namespace ContainerAv6qDYj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jobd8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._jobd8_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._jobd8_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'transaction' => ['privates', '.errored..service_locator._jobd8_.App\\Entity\\Transactions', NULL, 'Cannot autowire service ".service_locator._jobd8_": it needs an instance of "App\\Entity\\Transactions" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'transaction' => 'App\\Entity\\Transactions',
        ]);
    }
}
