<?php

namespace ContainerAv6qDYj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2RfZvHwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2RfZvHw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2RfZvHw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::deleteCategory' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\AdminController::deleteTransaction' => ['privates', '.service_locator._jobd8_', 'get_ServiceLocator_Jobd8Service', true],
            'App\\Controller\\AdminController::deleteUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\AdminController::editCategory' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\AdminController::editUser' => ['privates', '.service_locator.H38vlv9', 'get_ServiceLocator_H38vlv9Service', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::newCategory' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::newUser' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\AdminController::toggleAdmin' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\AdminController::transactions' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\TransactionsController::delete' => ['privates', '.service_locator._jobd8_', 'get_ServiceLocator_Jobd8Service', true],
            'App\\Controller\\TransactionsController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TransactionsController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TransactionsController::updateTransactions' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:deleteCategory' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\AdminController:deleteTransaction' => ['privates', '.service_locator._jobd8_', 'get_ServiceLocator_Jobd8Service', true],
            'App\\Controller\\AdminController:deleteUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\AdminController:editCategory' => ['privates', '.service_locator.WoAniWU', 'get_ServiceLocator_WoAniWUService', true],
            'App\\Controller\\AdminController:editUser' => ['privates', '.service_locator.H38vlv9', 'get_ServiceLocator_H38vlv9Service', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:newCategory' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:newUser' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\AdminController:toggleAdmin' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\AdminController:transactions' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\TransactionsController:delete' => ['privates', '.service_locator._jobd8_', 'get_ServiceLocator_Jobd8Service', true],
            'App\\Controller\\TransactionsController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TransactionsController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TransactionsController:updateTransactions' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::deleteCategory' => '?',
            'App\\Controller\\AdminController::deleteTransaction' => '?',
            'App\\Controller\\AdminController::deleteUser' => '?',
            'App\\Controller\\AdminController::editCategory' => '?',
            'App\\Controller\\AdminController::editUser' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::newCategory' => '?',
            'App\\Controller\\AdminController::newUser' => '?',
            'App\\Controller\\AdminController::toggleAdmin' => '?',
            'App\\Controller\\AdminController::transactions' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\TransactionsController::delete' => '?',
            'App\\Controller\\TransactionsController::index' => '?',
            'App\\Controller\\TransactionsController::new' => '?',
            'App\\Controller\\TransactionsController::updateTransactions' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:deleteCategory' => '?',
            'App\\Controller\\AdminController:deleteTransaction' => '?',
            'App\\Controller\\AdminController:deleteUser' => '?',
            'App\\Controller\\AdminController:editCategory' => '?',
            'App\\Controller\\AdminController:editUser' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:newCategory' => '?',
            'App\\Controller\\AdminController:newUser' => '?',
            'App\\Controller\\AdminController:toggleAdmin' => '?',
            'App\\Controller\\AdminController:transactions' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\TransactionsController:delete' => '?',
            'App\\Controller\\TransactionsController:index' => '?',
            'App\\Controller\\TransactionsController:new' => '?',
            'App\\Controller\\TransactionsController:updateTransactions' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
