<?php

namespace ContainerAv6qDYj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._jobd8_.App\Entity\Transactions' shared service.
     *
     * @return \App\Entity\Transactions
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._jobd8_": it needs an instance of "App\\Entity\\Transactions" but this type has been excluded in "config/services.yaml".');
    }
}
