<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAv6qDYj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAv6qDYj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAv6qDYj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAv6qDYj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAv6qDYj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Av6qDYj',
    'container.build_id' => '826727a5',
    'container.build_time' => 1765389562,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAv6qDYj');
